---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    requirements-file: requirements.yml
driver:
  name: docker
platforms:
  - name: instance-debian12
    image: robertdebock/debian:bookworm
    command: /sbin/init
    pre_build_image: true
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  - name: instance-ubuntu-2204-default
    image: robertdebock/ubuntu:jammy
    command: /sbin/init
    pre_build_image: true
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  - name: instance-ubuntu-2204-pg17
    image: robertdebock/ubuntu:jammy
    command: /sbin/init
    pre_build_image: true
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto
      roles_path: ${MOLECULE_PROJECT_DIRECTORY}/..
verifier:
  name: testinfra
